/*
 * Generated by the Mule project wizard. http://mule.mulesoft.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.tools.jaas;

import org.mule.api.MuleMessage;
import org.mule.construct.SimpleFlowConstruct;
import org.mule.module.client.MuleClient;
import org.mule.tck.FunctionalTestCase;
import org.mule.transport.NullPayload;

import java.util.HashMap;

public class JavaDocAsAServiceTestCase extends FunctionalTestCase
{
    protected String getConfigResources()
    {
        return "jaas-functional-test-config.xml";
    }

    public void testInboundEndpoint() throws Exception
    {
        SimpleFlowConstruct flow = lookupFlowConstruct("main");
        MuleMessage message = flow.process(getTestEvent(null)).getMessage();
        assertTrue(message.getPayload() instanceof Object);

    }

    private SimpleFlowConstruct lookupFlowConstruct(String name)
    {
        return (SimpleFlowConstruct) muleContext.getRegistry().lookupFlowConstruct(name);
    }

}
